apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/products.yaml
      - ./k8s/auth.yaml
      - ./k8s/orders.yaml
      # - ./k8s/frontend.yaml
      - ./k8s/ingress.yaml
build:
  local:
    push: false
    useDockerCLI: true 
  artifacts:
    - image: foodshop-products-dev # image name
      context: products # dirname
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "**/*.ts"
          dest: .

    - image: foodshop-auth-dev # image name
      context: auth # dirname
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "**/*.ts"
          dest: .

    - image: foodshop-orders-dev # image name
      context: orders # dirname
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "**/*.ts"
          dest: .


    # - image: foodshop-frontend-dev # image name
    #   context: frontend # dirname
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #     - src: "**/*.ts"
    #       dest: .